In [119]:
import numpy as np

NameError: name 'time' is not defined

In [4]:
a = [1,2,3,4,5,6,4,7]
type(a)

list

In [120]:
arr = np.array(a,float)

NameError: name 'time' is not defined

In [6]:
type(arr)
arr

array([1., 2., 3., 4., 5., 6., 4., 7.])

In [7]:
arr2  = np.array([[1,2,3,4,5],[9,8,6,7,3]])
arr2[0,-1]

5

In [8]:
arr2.shape
arr2.ndim

2

In [9]:
arr3 = np.array([[[1,2,3,4,5],[9,8,7,6,0]],[[1,2,3,4,5],[4,3,2,7,6]]])

In [10]:
arr3.shape

(2, 2, 5)

In [11]:
arr4 = ([1,2,3,4,5])
sume = arr4[2]+arr4[3]
print(sume)



7


In [12]:
arr5 = np.array([[[1,2,3]],[[5,6,7]],[[7,8,9]],[[10,11,12]],[[13,14,15]]])
arr6 = np.array([[[16,17,18]],[[19,20,21]],[[22,23,24]],[[25,26,27]],[[28,29,30]]])
arr7 =np.min(arr5,axis=0)
print(arr7)

[[1 2 3]]


In [13]:
arr5.shape

(5, 1, 3)

In [14]:
arr5[4,0,2].dtype

dtype('int32')

In [15]:
arr2[0,-2]


4

In [16]:
arr2[0,-3]


3

In [17]:
arr2[0,-4]


2

In [18]:
arr2[0,-5]


1

In [19]:
arr2[1,-1]


3

In [20]:
arr2[1,-2]


7

In [21]:
arr2[1,-3]


6

In [22]:
arr2[1,-4]


8

In [23]:
arr2[1,-5]

9

## str(),float(),Complex()

In [24]:
arr69 = np.array(["abc","xyz"])
arr69.dtype

dtype('<U3')

In [25]:
art = np.arange(2,21,2)
art

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
np.zeros(5)
np.ones(4)

array([1., 1., 1., 1.])

In [27]:
art.reshape(2,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [28]:
arrpr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [29]:
arrpr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [30]:
arrpr.shape

(4, 4)

In [31]:
arrpr[1,-1]

8

In [32]:
arrpr2 = arrpr.T

In [33]:
arrpr2

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [34]:
arrpr2.reshape(2,8)

array([[ 1,  5,  9, 13,  2,  6, 10, 14],
       [ 3,  7, 11, 15,  4,  8, 12, 16]])

In [35]:
np.arange(78,858,78)

array([ 78, 156, 234, 312, 390, 468, 546, 624, 702, 780])

In [36]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [37]:
arrpr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
arrpr.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [39]:
for i in arrpr:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [40]:
a = np.array([[1,2,3,4],[5,6,7,8]])
for i in a:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [41]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [42]:
a2 =a.reshape(1,8)
a2

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [43]:
ar1 = np.array([1,2,3,4,5,6,7,8,]).reshape(2,4)
ar2 = np.array([9,10,11,12,13,14,15,16]).reshape(2,4)

## axis:1= row,0=Column 

In [44]:
np.concatenate((ar1,ar2),axis =1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [45]:
np.stack((ar1,ar2),axis =1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

In [46]:
np.vstack((ar1,ar2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
np.hstack((ar1,ar2))

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [48]:
np.insert(ar1,3,[69])

array([ 1,  2,  3, 69,  4,  5,  6,  7,  8])

In [49]:
np.delete(ar1,3)

array([1, 2, 3, 5, 6, 7, 8])

In [50]:
np.empty((5,5), dtype = int)

array([[1060562760,        547,         58,          0,          0],
       [         0,          0,          0,          0,         53],
       [1852990827,  909012069, 1667393078,  761357365, 1631085666],
       [ 875836461, 1647848760, 1663918438,  842281318,  909129265],
       [ 775173176, 1667594341, 1600484469, 1970496882, 1700951148]])

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
np.arange(45,451,45)

array([ 45,  90, 135, 180, 225, 270, 315, 360, 405, 450])

In [56]:
np.linspace(1,2,100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [57]:
np.random.rand(3)

array([0.91359866, 0.71622541, 0.1875617 ])

## Vectorization

In [58]:
x = list(range(1,11))
x*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [59]:
v = np.arange(1,11)
v+100


array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

## Vectorization with Comparison Operators 

In [60]:
arrv = np.arange(3,20,4)
arrv

array([ 3,  7, 11, 15, 19])

In [61]:
arrv>4

array([False,  True,  True,  True,  True])

In [62]:
mask = arrv%1 ==0
arrv[mask]

array([ 3,  7, 11, 15, 19])

In [63]:
name = np.array(['raj','avinash','bala','amit','raju','sandip'])
name =='raj'
mask = name=='raj'
name[mask]

array(['raj'], dtype='<U7')

In [64]:
name[name =='bala']



array(['bala'], dtype='<U7')

In [65]:
c1 = (name!='raj')
c2 = (name!='bala')
c1 & c2

array([False,  True, False,  True,  True,  True])

In [66]:
c1 | c2


array([ True,  True,  True,  True,  True,  True])

In [67]:
name[(name !='raj') & (name !='bala')]

array(['avinash', 'amit', 'raju', 'sandip'], dtype='<U7')

In [68]:
name[(name !='raj') | (name !='bala')]

array(['raj', 'avinash', 'bala', 'amit', 'raju', 'sandip'], dtype='<U7')

In [69]:
name == "raj"
name[name=='raj']="Shiv"
name

array(['Shiv', 'avinash', 'bala', 'amit', 'raju', 'sandip'], dtype='<U7')

In [108]:
dm = np.array([[1,2],[3,4]])

In [109]:
dm.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [130]:
dm2 = np.array([[1,2],[3,4]])
for i in dm2:
    print(i)

[1 2]
[3 4]


In [112]:
dm2.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [123]:
a = np.add(dm,dm2)

array([[2, 4],
       [6, 8]])

In [129]:
# np.mean(a)
# np.std(a)
np.sum(a,axis =1)

array([10, 26])

In [89]:
np.subtract(dm,dm2)


array([[-3, -6, -1],
       [-1,  2, -3],
       [ 5,  7,  2]])

In [114]:
np.multiply(dm,dm2)


array([[ 1,  4],
       [ 9, 16]])

In [93]:
np.divide(dm,dm2)

array([[0.25      , 0.25      , 0.75      ],
       [0.8       , 1.66666667, 0.66666667],
       [3.5       , 8.        , 1.28571429]])

In [96]:
m = dm*dm2
m

array([[ 4, 16, 12],
       [20, 15, 54],
       [14,  8, 63]])

In [101]:
ac = np.array([[1,2,3],[4,5,6]])
ac

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
ac2 = np.array([[10,11],[20,21],[30,31]])
ac2

array([[10, 11],
       [20, 21],
       [30, 31]])

In [107]:
np.dot(ac,ac2)

array([[140, 146],
       [320, 335]])

In [118]:
time(np.dot(dm,dm2))

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 7, 10],
       [15, 22]])

In [117]:
time(np.matmul(dm,dm2))

CPU times: total: 0 ns
Wall time: 3.04 ms


array([[ 7, 10],
       [15, 22]])

In [121]:
z =np.ones([9,5,7,4])
b = np.ones([9,5,7,4])
np.dot(z,b).shape

ValueError: shapes (9,5,7,4) and (9,5,7,4) not aligned: 4 (dim 3) != 7 (dim 2)

In [122]:
np.kron([1,2,3],[5,2,3])

array([ 5,  2,  3, 10,  4,  6, 15,  6,  9])