In [1]:
import numpy as np

In [3]:
a=np.arange(21,31)
a

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [4]:
a[0]

21

In [5]:
a[-1]

30

In [6]:
a[2:5]

array([23, 24, 25])

In [7]:
b=np.arange(1,10).reshape(3,3)

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b[1][1]

5

In [10]:
b[1,1]

5

In [11]:
b[1]

array([4, 5, 6])

In [12]:
b[2]

array([7, 8, 9])

In [13]:
b[3,3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [14]:
b[2,2]

9

In [15]:
b[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [16]:
b[:1,:1]

array([[1]])

In [17]:
b[0:,0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b[0::2,0::2]

array([[1, 3],
       [7, 9]])

In [19]:
# vectorization & selection in array

In [20]:
list1=list(range(1,10))

In [21]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
list1*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
list1+2

TypeError: can only concatenate list (not "int") to list

In [25]:
a*2

array([42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [26]:
b*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [27]:
b-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [28]:
a-2

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [29]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#comparison operator

In [31]:
b>4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [32]:
#masking
mask=b>4
b[mask]

array([5, 6, 7, 8, 9])

In [33]:
b[b>4]

array([5, 6, 7, 8, 9])

In [34]:
even=(b%2==0)

In [35]:
b[even]

array([2, 4, 6, 8])

In [36]:
names=np.array(["abc",'raj',"suraj",'jay','kumar','jay'])

In [37]:
names

array(['abc', 'raj', 'suraj', 'jay', 'kumar', 'jay'], dtype='<U5')

In [38]:
names[names=="jay"]

array(['jay', 'jay'], dtype='<U5')

In [39]:
names[names!="jay"]

array(['abc', 'raj', 'suraj', 'kumar'], dtype='<U5')

In [40]:
names[names=='jay','raj']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [46]:
con1=(names!='jay')
con2=(names=='raj')

names[(con1) & (con2)]


array(['raj'], dtype='<U5')

In [49]:
names[(names=='jay') | (names=='raj')]

array(['raj', 'jay', 'jay'], dtype='<U5')

In [50]:
names[~(names=='jay')]

array(['abc', 'raj', 'suraj', 'kumar'], dtype='<U5')

In [51]:
names[~(names=='jay')]='jay'

In [52]:
names

array(['jay', 'jay', 'jay', 'jay', 'jay', 'jay'], dtype='<U5')

In [53]:
np.unique(names)

array(['jay'], dtype='<U5')