In [1]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [2]:
type(a)

list

In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr2 = np.array((1, 2, 3, 4, 5))
print(arr2)

[1 2 3 4 5]


In [7]:
arr1 = np.array((1))
print(arr)#

[1 2 3 4 5]


In [8]:
a2=np.array(arr2,float)

In [9]:
a2

array([1., 2., 3., 4., 5.])

In [10]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [11]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
arr3.size

12

In [13]:
arr3.shape

(2, 2, 3)

In [14]:
arr3.ndim

3

In [15]:
arr4 = np.array([1, 2, 3, 4],ndmin=5)

print(arr4)

[[[[[1 2 3 4]]]]]


In [16]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [17]:
arr[2]+arr[2]

6

In [18]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [19]:
arr3[0,2]

3

In [20]:
arr3[1,2]

6

In [21]:
ar = np.array([[[1,2,3],[14,15,6]],[[11,22,3],[44,25,6]],[[31,42,3],[45,55,6]]])
print(ar)

[[[ 1  2  3]
  [14 15  6]]

 [[11 22  3]
  [44 25  6]]

 [[31 42  3]
  [45 55  6]]]


In [22]:
ar[1,0,0]

11

In [23]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [24]:
arr3[1,-1]

6

In [25]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [26]:
print(arr[1:3])

[2 3]


In [27]:
print(arr[:3])

[1 2 3]


In [28]:
print(arr[1:])

[2 3 4 5]


In [29]:
arr.dtype

dtype('int32')

In [30]:
ar1 = np.array([1.1, 2.6, 3.5, 4.8, 5.9])
print(ar1)

[1.1 2.6 3.5 4.8 5.9]


In [31]:
ar1.dtype

dtype('float64')

In [32]:
ar2 = np.array(["abc","xyz", "lmn", "pqr","stu"])
print(ar2)

['abc' 'xyz' 'lmn' 'pqr' 'stu']


In [33]:
ar2.dtype

dtype('<U3')

In [34]:
a = np.array([1, 2, 3, 4, 5])

print(a)

[1 2 3 4 5]


In [35]:
a2=np.array(a,float)
a2

array([1., 2., 3., 4., 5.])

In [36]:
a3=np.array(a,str)
a3

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [37]:
a2=np.array(a,complex)
a2

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [38]:
a2=np.array(a,bool)
a2

array([ True,  True,  True,  True,  True])

In [39]:
list2=[1,2,0,0.5,-7]
a3=np.array(list2,bool)
a3

array([ True,  True, False,  True,  True])

In [40]:
x=np.arange(2,10)
type(x)

numpy.ndarray

In [41]:
a = np.array([1, 2, 3, 4, 5,6,7,8])
newar=a.reshape(2,2,2)
print(newar)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
a = np.array([[1, 2, 3, 4],[ 5,6,7,8]])
newar=a.reshape(-5)
print(newar)

[1 2 3 4 5 6 7 8]


In [46]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [48]:
a = np.array([[1, 2, 3, 4],[ 5,6,7,8]])
for x in a:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [49]:
np.array([1,2,3,4,5,6]).reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a = np.array([1,2,3,4,5,6]).reshape(2, 3)
b = np.array([7,8,9,10,11,12]).reshape(2,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [53]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [63]:
np.stack((a,b),axis=1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [64]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
a = np.array([1,2,3,4,5,6])
np.append(a, [27, 28, 29])

array([ 1,  2,  3,  4,  5,  6, 27, 28, 29])

In [66]:
np.insert(a, 3, [1,2,3])

array([1, 2, 3, 1, 2, 3, 4, 5, 6])

In [70]:
np.delete(a,1)

array([1, 3, 4, 5, 6])

In [ ]:
#Array Creation Routine in Numpy

In [77]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [72]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.62047965e-321],
       [1.24610723e-306, 1.29061142e-306, 6.01346930e-154]])

In [73]:
np.empty((3,3), dtype=int)

array([[2003068144,        477,    3801155],
       [   5570652,    6619251,    7536754],
       [   6357084,    7143524,    7209065]])

In [74]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [79]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [83]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [84]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

np.linspace - This is a function similar to arange, instead of step size, the number of evenly spaced values between an interval is specified

In [86]:
np.linspace(11, 20,2)

array([11., 20.])

In [87]:
np.linspace(11, 20, 3)

array([11. , 15.5, 20. ])

In [88]:
np.linspace(11, 20, 10)

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [89]:
np.linspace(11, 20, 15)

array([11.        , 11.64285714, 12.28571429, 12.92857143, 13.57142857,
       14.21428571, 14.85714286, 15.5       , 16.14285714, 16.78571429,
       17.42857143, 18.07142857, 18.71428571, 19.35714286, 20.        ])

In [91]:
np.random.rand(10)

array([0.13745448, 0.49430289, 0.58266917, 0.19099235, 0.64533732,
       0.54841089, 0.12065613, 0.3972681 , 0.95912729, 0.01957683])

In [92]:
np.random.rand(3,3)

array([[0.55881534, 0.59860392, 0.77016967],
       [0.16726388, 0.47079364, 0.19235903],
       [0.01803934, 0.01860027, 0.57644634]])

np.random.randn - returns an array of spacified shape with random values between -ve to +ve

In [93]:
np.random.randn(3,3)

array([[ 2.14908844,  0.24344223, -0.35453136],
       [ 1.20553737,  0.57994321,  0.31632577],
       [ 0.92561709, -0.5351025 , -0.30621161]])

In [95]:
#Vectorization & Selection in an array

x = list(range(1,11))
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [99]:
type(x)

list

In [96]:
x*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [97]:
a = np.arange(1,11)

In [98]:
type(a)

numpy.ndarray

In [100]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [101]:
a+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [102]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [103]:
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [104]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

Vectorization with comparison operators

In [105]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
3>4

False

In [107]:
3<4

True

In [108]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [109]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [114]:
mask=a%2==0
mask

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [113]:
a[mask]

array([ 2,  4,  6,  8, 10])

In [115]:
names=np.array(["jay", "raj", "jay", "kumar", "mrityunjay", "kumar", "jay", "rohit", "suraj", "ravi"])

In [116]:
#select all the names, where the value is jay
names=="jay"

array([ True, False,  True, False, False, False,  True, False, False,
       False])

In [117]:
mask = names=="jay"

In [118]:
names[mask]

array(['jay', 'jay', 'jay'], dtype='<U10')

In [119]:
names[names=="jay"]

array(['jay', 'jay', 'jay'], dtype='<U10')

In [120]:
#select all the names, where the values is not jay
names[names!="jay"]

array(['raj', 'kumar', 'mrityunjay', 'kumar', 'rohit', 'suraj', 'ravi'],
      dtype='<U10')

In [121]:
#select all the names except jay and kumar 
cond1= (names!="jay")
cond2= (names!="kumar")

In [ ]:
#=> and operator
#here in numpy 
#and => &
#or  => |

In [122]:
cond1 & cond2

array([False,  True, False, False,  True, False, False,  True,  True,
        True])

In [123]:
cond1 | cond2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [124]:
names[cond1 & cond2]

array(['raj', 'mrityunjay', 'rohit', 'suraj', 'ravi'], dtype='<U10')

In [ ]:
names[(names!="jay")&(names!="kumar")]

In [125]:
#select all those naems where name is jay and kumar
names[(names=="jay")|(names=="kumar")]

array(['jay', 'jay', 'kumar', 'kumar', 'jay'], dtype='<U10')

In [126]:
#select all the values which is not mrityunjay, and assign then as shiv
#step1

names!="mrityunjay"

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [127]:
#step2
names[names!="mrityunjay"]

array(['jay', 'raj', 'jay', 'kumar', 'kumar', 'jay', 'rohit', 'suraj',
       'ravi'], dtype='<U10')

In [128]:
#step3
names[names!="mrityunjay"] = "shiv"

In [129]:
names

array(['shiv', 'shiv', 'shiv', 'shiv', 'mrityunjay', 'shiv', 'shiv',
       'shiv', 'shiv', 'shiv'], dtype='<U10')