# Slicing & Indexing of an array

In [1]:
import numpy as np

In [2]:
a =np.arange(21, 31)
a

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [3]:
a[2]

23

In [4]:
a[-1]

30

In [5]:
a[3: 6]

array([24, 25, 26])

## Indexing & Slicing on 2D array

In [6]:
a = np.arange(1,10).reshape(3,3)

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#index -> 4 => var[row, col]
a[1, 0]

4

In [9]:
a[1, 1]

5

In [10]:
a[0, 2]

3

In [12]:
#slicing => var[startrow: endrow, startcol: endcol]
#[[4,5],
#[7,8]]
a[1:, 0:2]

array([[4, 5],
       [7, 8]])

In [12]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
#[[6,7],
#[10,11]]

a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [14]:
#[[11, 12],
#[15, 16]]

a[2:, 2:]

array([[11, 12],
       [15, 16]])

In [16]:
a[0:2, 1:3]

array([[2, 3],
       [6, 7]])

# Tip

In [17]:
a = np.arange(1,11)

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
a[0:5]

array([1, 2, 3, 4, 5])

In [20]:
a[:5] #start is empty, this mean start from the begining, i.e 0

array([1, 2, 3, 4, 5])

In [21]:
a[5: ] #end is empty, this mean go till the end i.e include the very last element of the list

array([ 6,  7,  8,  9, 10])