# Arithmetical & Statistical Operations on Numpy Array

In [9]:
import numpy as np

In [10]:
a = np.array([[1, 5, 6], [1, 8, 9], [0, -1, 6]])
b = np.array([[4, 8, 4], [1, 0, 5], [6, -8, 3]])

In [11]:
a

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [12]:
b

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  3]])

## Arithmetics on numpy 

In [13]:
np.add(a,b)

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9,  9]])

In [14]:
np.subtract(a,b)

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  3]])

In [7]:
np.multiply(a,b)

array([[ 4, 40, 24],
       [ 1,  0, 45],
       [ 0,  8, 18]])

In [15]:
np.divide(a,b)

C:\Users\admin\AppData\Local\Temp\ipykernel_6740\2626738034.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 2.   ]])

In [16]:
np.remainder(a,b)

C:\Users\admin\AppData\Local\Temp\ipykernel_6740\1219048507.py:1: RuntimeWarning: divide by zero encountered in remainder
  np.remainder(a,b)


array([[ 1,  5,  2],
       [ 0,  0,  4],
       [ 0, -1,  0]])

#### Matrics product

In [17]:
#dot product or inner product i.e 1st row to 1st col and so on...
np.matmul(a,b)

array([[ 45, -40,  47],
       [ 66, -64,  71],
       [ 35, -48,  13]])

In [18]:
import numpy as np
a=np.ones([9,5,7,4])
b=np.ones([9,5,7,4])
np.dot(a,b).shape

ValueError: shapes (9,5,7,4) and (9,5,7,4) not aligned: 4 (dim 3) != 7 (dim 2)

In [5]:
import numpy as np
a=np.ones([9,5,7,4])
b=np.ones([9,5,7,4])
np.matmul(a,b).shape

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 7 is different from 4)

In [19]:
import numpy as np
n=np.kron([1,2,3],[5,2,3])
n

array([ 5,  2,  3, 10,  4,  6, 15,  6,  9])

In [20]:
np.kron(a,b)

array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
    

In [13]:
arr = np.arange(6)

In [14]:
arr

array([0, 1, 2, 3, 4, 5])

In [15]:
arr*10

array([ 0, 10, 20, 30, 40, 50])

In [16]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [17]:
nums = np.sqrt(arr)

In [18]:
np.ceil(nums)

array([0., 1., 2., 2., 2., 3.])

In [19]:
np.floor(nums)

array([0., 1., 1., 1., 2., 2.])

## Statistical Operations

In [20]:
arr = np.random.randn(4,2)
arr

array([[ 0.3914868 ,  0.50898752],
       [-1.54686239,  1.57582937],
       [-0.36974214,  1.13265326],
       [-0.5751543 , -0.83824835]])

In [21]:
arr.mean()

0.03486872137263135

In [22]:
arr.std()

0.9830882766423283

In [23]:
arr.max()

1.575829370765041

In [24]:
arr.argmax()

3

In [25]:
arr.min()

-1.54686239469609

In [26]:
arr.argmin()

2

In [27]:
arr

array([[ 0.3914868 ,  0.50898752],
       [-1.54686239,  1.57582937],
       [-0.36974214,  1.13265326],
       [-0.5751543 , -0.83824835]])

In [28]:
arr.sum()

0.2789497709810508

In [29]:
arr.sum(axis=0)

array([-2.10027202,  2.3792218 ])

In [30]:
arr.sum(axis=1)

array([ 0.90047432,  0.02896698,  0.76291112, -1.41340265])

In [31]:
arr

array([[ 0.3914868 ,  0.50898752],
       [-1.54686239,  1.57582937],
       [-0.36974214,  1.13265326],
       [-0.5751543 , -0.83824835]])

In [32]:
arr.flatten()

array([ 0.3914868 ,  0.50898752, -1.54686239,  1.57582937, -0.36974214,
        1.13265326, -0.5751543 , -0.83824835])

### Computing Euclidean Distance between 2 vectors

In [33]:
vec1 = np.random.randn(3,3)
vec2 = np.random.randn(3,3)

In [34]:
vec1

array([[ 0.28506059,  0.2152483 ,  0.00981245],
       [-1.35761018,  1.22715167,  2.87897773],
       [-0.79640432, -0.62535776, -1.37032551]])

In [35]:
vec2

array([[-0.20788294, -0.26501972, -1.23811134],
       [ 1.00346387, -0.14964034, -2.34876628],
       [ 1.08922863,  0.83495722, -0.46145889]])

In [36]:
dist = np.sqrt(np.sum(vec1-vec2)**2)

In [37]:
dist

2.2097827537258374

# Trigonometric Functions

In [38]:
np.sin(90)

0.8939966636005579

In [39]:
np.cos(90)

-0.4480736161291701

In [40]:
np.tan(30)

-6.405331196646276

In [41]:
np.log(10)

2.302585092994046

In [42]:
np.log(1)

0.0

In [43]:
np.log10(10)

1.0

In [44]:
np.log(np.log10(5))

-0.35814744992084513