# Array Creation Routine in Numpy

In [1]:
import numpy as np

#### 1. np.empty -: It creates an uninitialise array of specified shape with random values

In [2]:
np.empty(5)

array([5.53287538e-048, 6.01346953e-154, 4.03154054e+103, 2.94261135e-314,
       0.00000000e+000])

In [3]:
np.empty((3,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.29061074e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 0.00000000e+000]])

In [4]:
np.empty((3,3), dtype=int)

array([[1120715952,        742,  537537837],
       [1629495328, 1847605792, 1634890337],
       [ 538970745,  538976288, 1750343712]])

#### 2. np.zeros - It returns a new array of specified shape, filled with zeros

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### 3. np.ones - It returns a new array of specified shape, filled with ones

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 4. np.eye - it return an identity matrix which is a square matrix

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

#### 5. arange -: It returns an evenly spaced numbers just like python range function

In [11]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
np.arange(1,11)
#start: inclusive, end: exclusive

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [26]:
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

#### 6. np.linspace - This is a function similar to arange, instead of step size, the number of evenly spaced values between an interval is specified

In [29]:
np.linspace(11, 20,2)

array([11., 20.])

In [31]:
np.linspace(11, 20, 3)

array([11. , 15.5, 20. ])

In [17]:
11.47368421 - 11

0.47368421000000005

In [18]:
 11.94736842 -   11.47368421

0.47368421000000005

In [19]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

#### 7. np.random.rand - returns an array of specified shape with random values between 0-1

In [33]:
np.random.rand(10)

array([0.75740298, 0.70734844, 0.12926543, 0.71882877, 0.51075552,
       0.02038792, 0.6606827 , 0.98410514, 0.62031327, 0.00722705])

In [21]:
np.random.rand(3,3)

array([[0.38550011, 0.10105953, 0.4464894 ],
       [0.35297952, 0.69733264, 0.30518085],
       [0.89375986, 0.21983257, 0.03448373]])

#### 8. np.random.randn - returns an array of spacified shape with random values between -ve to +ve

In [34]:
np.random.randn(10)

array([-1.1004544 ,  0.33552682,  2.63635327, -0.29089981,  0.49518174,
        0.04064662, -0.20678821,  0.07713252, -2.15781434, -0.7949085 ])

In [23]:
np.random.randn(3,3)

array([[-0.70768659,  0.14447009,  1.15558398],
       [ 1.19984217,  1.83996689,  1.19925363],
       [-1.00453893, -0.75665716,  1.61713878]])