# Vectorization & Selection in an array

In [1]:
x = list(range(1,11))
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
x*2 #replication

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
import numpy as np

In [3]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
a+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

# Vectorization with comparison operators

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
3>4

False

In [16]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

### masking

In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
#what are all those numbers which are greater then 4
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [4]:
mask = a>4

In [5]:
a[mask]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
#what are the even number in my array
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [7]:
mask = a%2==0
a[mask]

array([ 2,  4,  6,  8, 10])

- vectorisation with comparison operators will give you the boolean value i.e True or False
- Masking will give you the actual value for which the condition was True

### Selection in array 

In [9]:
names=np.array(["jay", "raj", "jay", "kumar", "mrityunjay", "kumar", "jay", "rohit", "suraj", "ravi"])

In [10]:
#select all the names, where the value is jay
names=="jay"

array([ True, False,  True, False, False, False,  True, False, False,
       False])

In [11]:
mask = names=="jay"

In [12]:
names[mask]

array(['jay', 'jay', 'jay'], dtype='<U10')

In [13]:
names[names=="jay"]

array(['jay', 'jay', 'jay'], dtype='<U10')

In [14]:
#select all the names, where the values is not jay
names[names!="jay"]

array(['raj', 'kumar', 'mrityunjay', 'kumar', 'rohit', 'suraj', 'ravi'],
      dtype='<U10')

In [15]:
names

array(['jay', 'raj', 'jay', 'kumar', 'mrityunjay', 'kumar', 'jay',
       'rohit', 'suraj', 'ravi'], dtype='<U10')

In [16]:
#select all the names except jay and kumar 
cond1= (names!="jay")
cond2= (names!="kumar")

In [17]:
cond1

array([False,  True, False,  True,  True,  True, False,  True,  True,
        True])

In [18]:
cond2

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True])

In [33]:
#=> and operator
#here in numpy 
#and => &
#or  => |

In [34]:
cond1 & cond2

array([False,  True, False, False,  True, False, False,  True,  True,
        True])

In [35]:
names[cond1 & cond2]

array(['raj', 'mrityunjay', 'rohit', 'suraj', 'ravi'], dtype='<U10')

In [36]:
names[(names!="jay")&(names!="kumar")]

array(['raj', 'mrityunjay', 'rohit', 'suraj', 'ravi'], dtype='<U10')

In [37]:
#select all those naems where name is jay and kumar
names[(names=="jay")|(names=="kumar")]

array(['jay', 'jay', 'kumar', 'kumar', 'jay'], dtype='<U10')

In [38]:
#select all the values which is not mrityunjay, and assign then as shiv
#step1

names!="mrityunjay"

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [39]:
#step2
names[names!="mrityunjay"]

array(['jay', 'raj', 'jay', 'kumar', 'kumar', 'jay', 'rohit', 'suraj',
       'ravi'], dtype='<U10')

In [40]:
#step3
names[names!="mrityunjay"] = "shiv"

In [41]:
names

array(['shiv', 'shiv', 'shiv', 'shiv', 'mrityunjay', 'shiv', 'shiv',
       'shiv', 'shiv', 'shiv'], dtype='<U10')

In [42]:
np.unique(names)

array(['mrityunjay', 'shiv'], dtype='<U10')

# Summary

In [43]:
a #array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a*2 #vectorization with arithmetic operator

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [45]:
a>5 #vectorization with comparison operator

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [46]:
a[a>5] #masking 

array([ 6,  7,  8,  9, 10])