# Attributes & Function in Numpy

In [1]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
x = [1, 2, 3, 4, 5]

In [4]:
x

[1, 2, 3, 4, 5]

In [5]:
type(x)

list

In [6]:
a = np.array(x)

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
type(a)

numpy.ndarray

# Creating a numpy array of 2D

In [2]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

# Attributes & Methods of Numpy

#### 1. Shape -: return the shape of an array

In [10]:
a.shape  #row, col inside a tuple

(2, 3)

#### 2.size -: returns the total number of elements present in an array

In [11]:
a.size

6

#### 3.Transpose -: returns an by array by swaping the row into col & viz

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 4.NDim -: return the number of dimensions an array

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a.ndim

2

#### 5. Reshape-: used to change the shape of an array

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [14]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [15]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a= a.reshape(3,2)

In [22]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a.shape

(3, 2)

In [24]:
a.shape = (2, 3)

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6]])

# Functions in Numpy

In [26]:
np.array([1,2,3,4,5,6]).reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a = np.array([1,2,3,4,5,6]).reshape(2, 3)
b = np.array([7,8,9,10,11,12]).reshape(2,3)

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

#### 1. Concatenate((arr1, arr2)) -: used to join two different array together

In [30]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### 2. Vstack((arr1, arr2)) -: used to join two different array together vertically

In [31]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### 3. Hstack((arr1, arr2)) -: used to join two different array together horizontally

In [32]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [33]:
c = np.array([21, 22, 23, 24, 25, 26 ,26])

In [34]:
c

array([21, 22, 23, 24, 25, 26, 26])

#### 4. Append(arr, listofelement) -: used to add the elements in an array

In [35]:
np.append(c, [27, 28, 29])

array([21, 22, 23, 24, 25, 26, 26, 27, 28, 29])

#### 5. Insert(arr, index, element) -: used to add the elemenet in a specified position

In [36]:
c

array([21, 22, 23, 24, 25, 26, 26])

In [37]:
np.insert(c, 3, [1,2,3])

array([21, 22, 23,  1,  2,  3, 24, 25, 26, 26])

#### 6. Delete(arr, listofelementindexvalue) -: used to delete the elements of specified index

In [38]:
c

array([21, 22, 23, 24, 25, 26, 26])

In [39]:
np.delete(c,[-1])

array([21, 22, 23, 24, 25, 26])

In [40]:
c

array([21, 22, 23, 24, 25, 26, 26])

In [41]:
np.delete(c, [1, 2])

array([21, 24, 25, 26, 26])